import { ReactElement, useState } from 'react';
import { FormProvider, SubmitHandler, useForm } from 'react-hook-form';
import { toast } from 'react-hot-toast';
import Select from 'react-select';
import { yupResolver } from '@hookform/resolvers/yup';
import { Button } from '@ui/buttons';
import { Input } from '@ui/Input';
import Nav from '@ui/Nav';
import Tag from '@ui/Tag';
import { addHomepage, HomepageProps } from '@ui/Utils/HandleApi';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Layout } from 'src/layouts';
import * as Yup from 'yup';

import { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  const options = [
    { label: '1 Individual - N25,000.00', value: '1 Individual - N25,000.00' },
    {
      label: 'Group of 5 - 10% discount - N113,000.00',
      value: 'Group of 5 - 10% discount - N113,000.00',
    },
  ];

  const validationSchema = Yup.object().shape({
    // accountType: Yup.string().required('Required'),
    clubName: Yup.string()
      .min(2, 'Too Short!')
      .max(30, 'Too Long!')
      .required('Required'),
    districtNo: Yup.string()
      .min(3, 'Too Short!')
      .max(4, 'Too Long!')
      .required('Required'),
    email: Yup.string().email('Invalid email').required('Required'),
  });

  const DataForm = () => {
    const router = useRouter();
    const [selectedOption, setSelectedOption] = useState<any>(null);
    const [loading, setLoading] = useState(false);

    const methods = useForm<HomepageProps>({
      // @ts-ignore
      resolver: yupResolver(validationSchema),
    });

    const {
      formState: { isSubmitting, errors },
      handleSubmit,
      reset,
      setValue,
      register,
    } = methods;

    const onSubmit: SubmitHandler<HomepageProps> = async (value) => {
      console.log('Submit button clicked');
      console.log(value);
      try {
        setValue('accountType', selectedOption ? selectedOption.value : null);
        console.log('Form values after setting accountType:', value);
        await addHomepage(value);
        console.log('success');
        toast.success('successfully');
        reset();
        router.push('/registration');
      } catch (error) {
        console.log(error);
        toast.error('There is an error');
      }
    };

    return (
      <FormProvider {...methods}>
        <form className="container mx-[10%]" onSubmit={handleSubmit(onSubmit)}>
          <div className="grid w-[800px] grid-cols-2 gap-8 py-10">
            <Input
              label="Your District No. e.g 9110"
              {...register('districtNo')}
              disabled={isSubmitting}
              error={errors.districtNo?.message}
            />

            <Input
              label="Name of your club? e.g RC Omole-Golden"
              {...register('clubName')}
              disabled={isSubmitting}
              error={errors.clubName?.message}
            />

            <div className="w-full">
              <label className="text-sm font-medium">
                No of people to be Registered?
              </label>
              <Select
                {...register('accountType')}
                className="rounded-md border-2 border-black/40 transition-all "
                defaultValue={selectedOption}
                onChange={setSelectedOption}
                options={options}
              />
            </div>

            <Input
              {...register('email')}
              disabled={isSubmitting}
              error={errors.email?.message}
              label="Your email address"
            />
          </div>

          <div className="w-[273px]">
            <Button disabled={isSubmitting} type="submit" variants="primary">
              Next
            </Button>
          </div>
        </form>
      </FormProvider>
    );
  };
  return (
    <>
      <Head>
        <title>Rite Mate Project</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
        <link
          href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
          rel="stylesheet"
        ></link>
      </Head>
      <Nav />
      <main className="container mx-[10%]">
        <div>
          <h1 className="py-8 text-2xl font-medium">Registration</h1>
          <div className="h-16 w-[800px] rounded-xl bg-[#FAC476]/30">
            <div className="flex h-full items-center pl-4 tracking-wider">
              <li>
                Registration is N25,000 but register before 15th December 2023
                and get a 20% discount
              </li>
            </div>
          </div>
          <h1 className="py-4 text-3xl">How will you like to Register?</h1>
          <div className="flex gap-4 py-6">
            <Tag variants="tertiary">Group Registration</Tag>
            <Tag variants="secondary">Individual Registration</Tag>
          </div>
        </div>
      </main>
      <div className="h-[380px] bg-[#F0F0F0]">
        <DataForm />
      </div>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <Layout>{page}</Layout>;

export default Home;
